Entity/Survey.php
<?php

namespace ATM\SurveyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity
 * @ORM\Table(name="atm_survey")
 */
class Survey{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    private $name;

    /**
     * @ORM\Column(name="creation_date", type="datetime", nullable=false)
     */
    private $creation_date;

    /**
     * @ORM\OneToMany(targetEntity="Question", mappedBy="survey", cascade={"remove"})
     */
    protected $questions;

    /**
     * @ORM\Column(name="header_image", type="string", length=255, nullable=true)
     */
    private $header_image;

    /**
     * @ORM\Column(name="header_image_mobile", type="string", length=255, nullable=true)
     */
    private $header_image_mobile;

    /**
     * @ORM\Column(name="header_image_middle", type="string", length=255, nullable=true)
     */
    private $header_image_middle;

    /**
     * @ORM\Column(name="profile_image", type="string", length=255, nullable=true)
     */
    private $profile_image;

    /**
     * @ORM\Column(name="init_date", type="datetime", nullable=true)
     */
    private $init_date;

    /**
     * @ORM\Column(name="end_date", type="datetime", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\OneToMany(targetEntity="Answer", mappedBy="survey")
     */
    protected $answers;

    public function __construct()
    {
        $this->creation_date = new \DateTime();
        $this->questions = new ArrayCollection();
        $this->answers = new ArrayCollection();
        $this->init_date = new \DateTime();
        $this->end_date = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getCreationDate()
    {
        return $this->creation_date;
    }

    public function setCreationDate($creation_date)
    {
        $this->creation_date = $creation_date;
    }

    public function getQuestions()
    {
        return $this->questions;
    }

    public function addQuestion($question)
    {
        $this->questions->add($question);
    }

    public function removeQuestion($question){
        $this->questions->removeElement($question);
    }

    public function getHeaderImage()
    {
        return $this->header_image;
    }

    public function setHeaderImage($header_image)
    {
        $this->header_image = $header_image;
    }

    public function getProfileImage()
    {
        return $this->profile_image;
    }

    public function setProfileImage($profile_image)
    {
        $this->profile_image = $profile_image;
    }

    public function getInitDate()
    {
        return $this->init_date;
    }

    public function setInitDate($init_date)
    {
        $this->init_date = $init_date;
    }

    public function getEndDate()
    {
        return $this->end_date;
    }

    public function setEndDate($end_date)
    {
        $this->end_date = $end_date;
    }

    public function getAnswers()
    {
        return $this->answers;
    }

    public function getHeaderImageMobile()
    {
        return $this->header_image_mobile;
    }

    public function setHeaderImageMobile($header_image_mobile)
    {
        $this->header_image_mobile = $header_image_mobile;
    }

    public function getHeaderImageMiddle()
    {
        return $this->header_image_middle;
    }

    public function setHeaderImageMiddle($header_image_middle)
    {
        $this->header_image_middle = $header_image_middle;
    }
}

Form/SurveyType.php
<?php

namespace ATM\SurveyBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use ATM\SurveyBundle\Entity\Survey;

class SurveyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class,array('required'=>true))
            ->add('init_date',DateTimeType::class, array(
                'required' => true,
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd-MM-yyyy',
                'attr' => array(
                    'class' => 'datepicker',
                    'placeholder' => 'Init date',
                    'autocomplete' => 'off'
                ),
            ))
            ->add('end_date',DateTimeType::class, array(
                'required' => true,
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'dd-MM-yyyy',
                'attr' => array(
                    'class' => 'datepicker',
                    'placeholder' => 'End date',
                    'autocomplete' => 'off'
                ),
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Survey::class
        ));
    }

    public function getBlockPrefix()
    {
        return 'atm_survey';
    }
}

Controller/SurveyController.php
<?php

namespace ATM\SurveyBundle\Controller;

use ATM\SurveyBundle\Event\InteractiveQuestionAnswered;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;
use ATM\SurveyBundle\Entity\Answer;
use ATM\SurveyBundle\Entity\InteractiveQuestion;
use ATM\SurveyBundle\Event\InteractiveQuestionsCreated;
use ATM\SurveyBundle\Event\SurveyCompleted;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use \DateTime;

class SurveyController extends Controller
{
    /**
     * @Route("/survey/for/users", name="atm_survey_for_users")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $configuration = $this->getParameter('atm_survey_config');

        $users = $em->getRepository($configuration['user'])->findAll();
        $surveys = $em->getRepository('ATMSurveyBundle:Survey')->findAll();


        return $this->render('ATMSurveyBundle:Frontend:index.html.twig',array(
            'users' => $users,
            'surveys' => $surveys
        ));
    }

    /**
     * @Route("/survey/users/{surveyId}/{userId}", name="atm_survey_user")
     */
    public function surveyUserAction($surveyId,$userId){
        $em = $this->getDoctrine()->getManager();
        $configuration = $this->getParameter('atm_survey_config');

        $qb = $em->createQueryBuilder();
        $qb
            ->select('answer')
            ->addSelect('survey')
            ->from('ATMSurveyBundle:Answer','answer')
            ->join('answer.survey','survey','WITH',$qb->expr()->eq('survey.id',$surveyId))
            ->join('answer.user','user','WITH',$qb->expr()->eq('user.id',$userId));

        $answer = $qb->getQuery()->getResult();
        if(!empty($answer) && $answer[0]->getAnswers() && !$this->get('xlabs_mm_admin')->isMMAdmin()){
            return $this->redirect($this->get('router')->generate($configuration['redirect_route_after_survey']));
        }

        $user = $em->getRepository($configuration['user'])->findOneById($userId);

        $qbSurvey = $em->createQueryBuilder();
        $qbSurvey
            ->select('partial s.{id,name,creation_date}')
            ->addSelect('partial q.{id,question,type}')
            ->addSelect('partial a.{id,username,title,usernameCanonical,avatar}')
            ->addSelect('partial c.{id,choice}')
            ->from('ATMSurveyBundle:Survey','s')
            ->leftJoin('s.questions','q')
            ->leftJoin('q.askedBy','a')
            ->leftJoin('q.choices','c')
            ->where($qbSurvey->expr()->eq('s.id',$surveyId))
            ->orderBy('q.id','ASC')
        ;

        $survey = $qbSurvey->getQuery()->getArrayResult();

        $qbAnswer = $em->createQueryBuilder();
        $qbAnswer
            ->select('partial a.{id,answers_json}')
            ->from('ATMSurveyBundle:Answer','a')
            ->join('a.survey','s','WITH',$qbAnswer->expr()->eq('s.id',$surveyId))
            ->join('a.user','u','WITH',$qbAnswer->expr()->eq('u.id',$userId));

        $answer = $qbAnswer->getQuery()->getArrayResult();
        if(isset($answer[0])){
            $userAnswers = json_decode($answer[0]['answers_json'],true);
        }else{
            $userAnswers = array();
        }

        return $this->render('ATMSurveyBundle:Frontend:survey.html.twig',array(
            'user' => $user,
            'survey' => $survey[0],
            'user_answers' => $userAnswers
        ));
    }

    /**
     * @Route("/survey/submit/{surveyId}/{userId}", name="atm_survey_user_submit")
     */
    public function surveySubmitAction($surveyId,$userId){
        $em = $this->getDoctrine()->getManager();
        $configuration = $this->getParameter('atm_survey_config');

        $survey = $em->getRepository('ATMSurveyBundle:Survey')->findOneById($surveyId);
        $user = $em->getRepository($configuration['user'])->findOneById($userId);

        $qbAnswer = $em->createQueryBuilder();
        $qbAnswer
            ->select('partial a.{id,answers_json}')
            ->from('ATMSurveyBundle:Answer','a')
            ->join('a.survey','s','WITH',$qbAnswer->expr()->eq('s.id',$surveyId))
            ->join('a.user','u','WITH',$qbAnswer->expr()->eq('u.id',$userId));

        $answers = $qbAnswer->getQuery()->getOneOrNullResult();

        $request = $this->get('request_stack')->getCurrentRequest();
        $formData = $request->request->all();

        if($answers){
            $answers->setAnswersJson(json_encode($formData));
        }else{
            $answers = new Answer();
            $answers->setAnswersJson(json_encode($formData));
            $answers->setSurvey($survey);
            $answers->setUser($user);
        }


        $em->persist($answers);
        $em->flush();

        $event = new SurveyCompleted($survey,$answers,$user);
        $this->get('event_dispatcher')->dispatch(SurveyCompleted::NAME, $event);

        $configuration = $this->getParameter('atm_survey_config');
        return $this->redirect($this->get('router')->generate($configuration['redirect_route_after_survey']));
    }

    /**
     * @Route("/survey/autosave/{surveyId}/{userId}/{questionId}/{answerText}", name="atm_survey_autosave", options={"expose"=true})
     */
    public function surveyAutoSaveAnswersAction($surveyId,$userId,$questionId,$answerText){
        $em = $this->getDoctrine()->getManager();
        $configuration = $this->getParameter('atm_survey_config');

        $qbAnswer = $em->createQueryBuilder();
        $qbAnswer
            ->select('partial a.{id,answers_json}')
            ->from('ATMSurveyBundle:Answer','a')
            ->join('a.survey','s','WITH',$qbAnswer->expr()->eq('s.id',$surveyId))
            ->join('a.user','u','WITH',$qbAnswer->expr()->eq('u.id',$userId));

        $answer = $qbAnswer->getQuery()->getOneOrNullResult();

        if(!is_null($this->get('request_stack')->getCurrentRequest()->get('choice'))){
            $answerText = json_decode($answerText,true);
            $userAnswer = array('id'=>$questionId , 'choices'=>$answerText);
        }else{
            $answerText = urldecode($answerText);
            $userAnswer = array('id'=>$questionId , 'text'=>$answerText);
        }

        if($answer){
            $arrAnswers = $answer->getAnswersJson();
            if(!empty($answerText)){
                $arrAnswers['answers']['answer'.$questionId] = $userAnswer;
            }else{
                unset($arrAnswers['answers']['answer'.$questionId]);
            }
            $answer->setAnswersJson(json_encode($arrAnswers));
        }else{
            $survey = $em->getRepository('ATMSurveyBundle:Survey')->findOneById($surveyId);
            $user = $em->getRepository($configuration['user'])->findOneById($userId);

            $arrAnswers = array();
            $arrAnswers['answers'] = array('answer'.$questionId => $userAnswer);
            $answer = new Answer();
            $answer->setAnswersJson(json_encode($arrAnswers));
            $answer->setSurvey($survey);
            $answer->setUser($user);
        }

        $em->persist($answer);
        $em->flush();

        return new Response('ok');
    }

    /**
     * @Route("/submit/interactive/questions", name="atm_survey_submit_interactive_questions")
     */
    public function createInteractiveQuestionsAction(){
        $request = $this->get('request_stack')->getCurrentRequest();
        $em = $this->getDoctrine()->getManager();
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $configuration = $this->getParameter('atm_survey_config');

        if($request->getMethod() == 'POST'){
            $modelId = $request->get('model_id');
            $model = $em->getRepository($configuration['user'])->findOneById($modelId);

            $questions = $request->get('questions');
            foreach($questions as $question){
                if(!empty($question)){
                    $interactiveQuestion = new InteractiveQuestion();
                    $interactiveQuestion->setQuestion($question);
                    $interactiveQuestion->setModel($model);
                    $interactiveQuestion->setAuthor($user);
                    $em->persist($interactiveQuestion);
                }
            }

            $em->flush();

            $event = new InteractiveQuestionsCreated($user,$model);
            $this->get('event_dispatcher')->dispatch(InteractiveQuestionsCreated::NAME, $event);

            $this->get('session')->getFlashBag()->add('interactive_questions_submitted','Thanks for your questions');
            return $this->redirect($this->get('router')->generate('members_model_profile_interactive_questions',array(
                'usernameCanonical' => $model->getUsernameCanonical()
            )));
        }

        return $this->redirect($this->get('router')->generate('members_user_profile',array(
            'usernameCanonical' => $user->getUsernameCanonical()
        )));
    }

    /**
     * @Route("/interactive/question/{questionId}", name="atm_survey_interactive_question_answer")
     */
    public function answerInteractiveQuestionAction($questionId){
        $request = $this->get('request_stack')->getCurrentRequest();
        $em = $this->getDoctrine()->getManager();
        $user = $this->get('security.token_storage')->getToken()->getUser();

        $interactiveQuestion = $em->getRepository('ATMSurveyBundle:InteractiveQuestion')->findOneById($questionId);

        // Check question is approved
        if(!$interactiveQuestion->getQuestionReviewed())
        {
            throw new NotFoundHttpException('The requested question doesn´t exist.');
        }

        // Check model is the destinatary
        if($interactiveQuestion->getModel()->getId() != $user->getId())
        {
            throw new AccessDeniedException('You are not the destinatary of this question.');

Resources/views/Admin/Survey/create.html.twig
{% extends 'ATMSurveyBundle:Admin:base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/atmsurvey/css/jquery-ui.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmsurvey/css/jquery-ui.theme.min.css') }}" type="text/css"/>
    <style>
        .ui-state-default{width: 100% !important;text-align: center !important;}
        .fr-view {font-family:"Quicksand", sans-serif !important;}
    </style>
{% endblock stylesheets %}


{% block content %}
    <div class="inner">
        <form action="{{ path('atm_survey_create') }}" method="post">
            <fieldset style="margin-bottom:20px;">
                <legend>Create Survey</legend>
                {{ form_widget(form.name) }}
            </fieldset>
            <fieldset style="margin-bottom:20px;">
                <legend>Init date</legend>
                {{ form_widget(form.init_date) }}
            </fieldset>
            <fieldset style="margin-bottom:20px;">
                <legend>End date</legend>
                {{ form_widget(form.end_date) }}
            </fieldset>
            {{ form_rest(form) }}
            <input type="submit" class="but blue" value="Save">
        </form>
    </div>
{% endblock content %}

{% block javascripts %}
    <script src="{{ asset('bundles/atmsurvey/js/jquery-ui.min.1121.js') }}"></script>
    <script>
        let dateFormat = 'dd-mm-yy';
        let from = $( "#atm_survey_init_date" )
            .datepicker({
                dateFormat: dateFormat,
                defaultDate: "+1w",
                changeMonth: true,
                numberOfMonths: 3
            }).on( "change", function() {
                to.datepicker( "option", "minDate", getDate( this ) );
            }),
            to = $( "#atm_survey_end_date" ).datepicker({
                dateFormat: dateFormat,
                defaultDate: "+1w",
                changeMonth: true,
                numberOfMonths: 3
            }).on( "change", function() {
                from.datepicker( "option", "maxDate", getDate( this ) );
            });

            function getDate( element ) {
                var date;
                try {
                    date = $.datepicker.parseDate( dateFormat, element.value );
                } catch( error ) {
                    date = null;
                }

                return date;
            }
    </script>
{% endblock javascripts %}

Resources/views/Admin/Survey/edit_questions.html.twig
{% extends 'ATMSurveyBundle:Admin:base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/atmsurvey/plugins/bootstrap/modal/modal.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/atmsurvey/css/jquery-ui.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmsurvey/css/jquery-ui.theme.min.css') }}" type="text/css"/>
    <style>
        .ui-state-default{width: 100% !important;text-align: center !important;}
        .fr-view {font-family:"Quicksand", sans-serif !important;}
    </style>
{% endblock stylesheets %}

{% block headingJS %}
    <script src="{{ asset('bundles/atmsurvey/plugins/bootstrap/modal/modal.js') }}"></script>
    <script src="{{ asset('bundles/atmsurvey/plugins/bootstrap/modal/bootstrap.bundle.js') }}"></script>
{% endblock headingJS %}

{% block content %}
    <div class="inner">
        <form action="{{ path('atm_survey_edit_questions',{ 'surveyId':survey.id }) }}" method="post" id="frmQuestions" enctype="multipart/form-data">
            <fieldset>
                <legend>Questions for survey: <span style="font-weight: bold;">{{ survey.name | title }}</span></legend>
            </fieldset>
            <fieldset style="width: 50%;float: left;min-height: 100px;margin-bottom: 40px;padding-bottom: 10px;border-bottom: 1px solid #c2c2c2;">
                <legend style="margin-bottom:15px;">Header Image</legend>
                <img src="{{ asset(survey.headerImage) }}" style="float: none;max-width: 100%">
                <input type="file" name="flHeaderImage" class="flImage">
            </fieldset>
            <fieldset style="width: 50%;float: left;min-height: 100px;margin-bottom: 40px;padding-bottom: 10px;border-bottom: 1px solid #c2c2c2;">
                <legend style="margin-bottom:15px;">Header Image Mobile (420x280)</legend>
                <img src="{{ asset(survey.headerImageMobile) }}" style="float: none;max-width: 100%">
                <input type="file" name="flHeaderImageMobile" class="flImage">
            </fieldset>
            <fieldset style="width: 50%;float: left;min-height: 100px;margin-bottom: 40px;padding-bottom: 10px;border-bottom: 1px solid #c2c2c2;margin-top:20px;">
                <legend style="margin-bottom:15px;">Header Image Middle (1440 x 478)</legend>
                <img src="{{ asset(survey.headerImageMiddle) }}" style="float: none;max-width: 100%">
                <input type="file" name="flHeaderImageMiddle" class="flImage">
            </fieldset>
            <fieldset style="width: 50%;float: left;min-height: 100px;margin-bottom: 40px;padding-bottom: 10px;border-bottom: 1px solid #c2c2c2;">
                <legend style="margin-bottom:15px;">Profile Image</legend>
                <img src="{{ asset(survey.profileImage) }}" style="float: none;max-width: 100%">
                <input type="file" name="flProfileImage" class="flImage">
            </fieldset>
            <fieldset>
                <legend>Publish Date</legend>
                <input type="text" name="publishDate" id="atm_survey_publish_date" value="{{ survey.publish_date }}">
            </fieldset>
            <input type="hidden" name="questions" id="hdnQuestions">
            <div class="controls" style="width: 70%;display: block;margin: 0 auto;">
                <a class="but blue btnAddQuestion" style="float: left;">Add Question</a>
                <a class="but red btnSaveQuestions" style="float: right;">Save Questions</a>
                <div class="clear"></div>
            </div>
            <div class="questions_container">
                {% for question in survey.questions %}
                    <div class="question" id="question_{{ question.id }}" data-question-id="{{ question.id }}">
                        <a class="but btnRemoveQuestion" data-question-id="{{ question.id }}">Remove</a>
                        <div class="selectC">
                            <select class="slcQuestionType">
                                <option value="text" {{ question.type == 'text' ? 'selected' }}>Text</option>
                                <option value="single_choice" {{ question.type == 'single_choice' ? 'selected' }}>Single Choice</option>
                                <option value="multiple_choice" {{ question.type == 'multiple_choice' ? 'selected' }}>Multiple Choice</option>
                            </select>
                        </div>
                        <textarea class="question_text" required>{{ question.question }}</textarea>
                        <div class="typeContainer" style="{{ question.type == 'text' ? 'display:none' }}">
                            <a class="but red addChoice">Add Choice</a>
                            <div class="choice_container">
                                {% for choice in question.choices %}
                                    <div>
                                        <label>
                                            {% if question.type == 'single_choice' %}
                                                <input type="radio" name="question_{{ question.id }}_rd" value="">
                                            {% else %}
                                                <input type="checkbox" name="question_{{ question.id }}_chk_{{ loop.index }}" value="">
                                            {% endif %}
                                            <span class="choiceText" data-choice-id="{{ choice.id }}">{{ choice.choice }}</span>
                                        </label>
                                        <span class="removeChoice" data-choice-id="{{ choice.id }}">X</span>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>
                    </div>
                {% endfor %}
            </div>
            <div class="controls" style="width: 70%;display: block;margin: 0 auto;">
                <a class="but blue btnAddQuestion" style="float: left;">Add Question</a>
                <a class="but red btnSaveQuestions" style="float: right;">Save Questions</a>
                <div class="clear"></div>
            </div>
        </form>
    </div>
    <div class="question_clone" style="display:none">
        <a class="but" onclick="$(this).parent().remove();">Remove Question</a>
        <div class="selectC">
            <select class="slcQuestionType">
                <option value="text" selected>Text</option>
                <option value="single_choice">Single Choice</option>
                <option value="multiple_choice">Multiple Choice</option>
            </select>
        </div>
        <textarea class="question_text" required></textarea>
        <div class="typeContainer" style="display:none">
            <a class="but red addChoice">Add Choice</a>
            <div class="choice_container"></div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="modal fade" id="popAddOption" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 style="font-weight: bold;">Option Text</h1>
                    <a class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">X</span>
                    </a>
                </div>
                <div class="modal-body">
                    <input type="text" id="txOptionText">
                </div>
                <div class="modal-footer">
                    <a class="but blue" id="btnSaveOption">Create option</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}
    <script src="{{ asset('bundles/atmsurvey/js/jquery-ui.min.1121.js') }}"></script>
    <script src="{{ asset('bundles/atmsurvey/js/survey.js') }}"></script>
    <script>
        $('.btnRemoveQuestion').click(function(){
            var btn = $(this);
            var questionId = btn.attr('data-question-id');

            $.ajax({
                url: Routing.generate('atm_survey_delete_question',{ 'questionId':questionId }),
                type: 'post',
                success: function(){
                    $('#question_'+questionId).remove();
                }
            });
        });

        $('.removeChoice').click(function(){
            var btn = $(this);
            var choiceId = btn.attr('data-choice-id');

            $.ajax({
                url: Routing.generate('atm_survey_delete_choice',{ 'choiceId':choiceId }),
                type: 'post',
                success: function(){
                    btn.parent().remove();
                }
            });
        });

        $('.btnSaveQuestions').click(function(){
            var questions = [];

            $('.questions_container .question').each(function() {
                var question = $(this);
                var obj = new Object();
                var questionId = question.attr('data-question-id');

                obj['text'] = question.find('.question_text').val();
                obj['type'] = question.find('.slcQuestionType').val();

                if (typeof questionId !== typeof undefined && questionId !== false) {
                    obj['id'] = questionId;
                }

                if(obj['type'] != 'text'){
                    var choicesContainer = question.find('.choice_container');
                    obj['choices'] = [];
                    choicesContainer.find('div').each(function(){
                        var choice = new Object();
                        var choiceId = $(this).find('.choiceText').attr('data-choice-id');
                        if (typeof choiceId !== typeof undefined && choiceId !== false) {
                            choice['id'] = choiceId;
                        }
                        choice['text'] = $(this).find('.choiceText').html();
                        obj['choices'].push(choice);
                    });
                }

                questions.push(obj);
            });

            $('#hdnQuestions').val(JSON.stringify(questions));
            $('#frmQuestions').submit();
        });

        $('.flImage').change(function(){
            var currentInput = $(this);
            var file = currentInput[0].files[0];

            var reader = new FileReader();
            reader.onload = function(e){
                currentInput.siblings('img').attr('src', e.target.result);
            };
            reader.readAsDataURL(file);
        });

        $( "#atm_survey_publish_date" ).datepicker({
            dateFormat: 'dd-mm-yy',
            changeMonth: true,
            numberOfMonths: 3
        });
    </script>
{% endblock javascripts %}

Resources/views/Admin/Survey/searchUsers.html.twig
{% for user in users %}
    <a class="user" data-survey-link="{{ url('atm_survey_user',{'userId':user.id,'surveyId':surveyId}) }}">{{ user.username }}</a>
{% endfor %}

Resources/views/Admin/Survey/seeForm.html.twig
{% extends 'ATMSurveyBundle:Admin:base.html.twig' %}

{% block content %}
    <div class="header">
        <img src="{{ asset(survey.header_image) }}">
        <img src="{{ asset(survey.profile_image) }}">
    </div>
    <div class="inner questions_form">
        <h1>{{ survey.name | title }}</h1>
        <ul>
            {% for question in survey.questions %}
                <li>
                    <p>{{ question.question }}</p>
                    {% if question.type != 'text' %}
                        <ul class="answer">
                        {% for choice in question.choices %}
                            <li>
                                <label>
                                    <input type="{{ question.type == 'single_choice' ? 'radio' : 'checkbox' }}" name="">
                                    {{ choice.choice }}
                                </label>
                            </li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <textarea name="" class="txAnswer"></textarea>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}